web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports: 
        - "80:80"
    volumes: 
        - ./raiz:/www
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links: 
        - php

php:
    build: .
    container_name: php-fpm
    volumes: 
        - ./raiz:/www
    links: 
        - db

db:
    image: mysql:5.7
    container_name: mysql
    ports: 
        - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: gustavo
        MYSQL_DATABASE: meularavel
        MYSQL_USER: gustavo
        MYSQL_PASSWORD: gustavo